name: Android CI

on:
  push:
    branches: [ master , dev , test ]
  pull_request:
    branches: [ master , dev , test ]
jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
  build:
    name: Creating Build New
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      - name: RunningOn
        run: echo ${{ github.ref }}
      - name: VersionTag
        run: echo ${{ steps.get_version.outputs.VERSION }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: app/build/intermediates/apk/debug/
      - name: Build debug apk
        run: ./gradlew clean assembleDebug
      - name: Create release and upload apk
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v5.0.7
          asset_path: app/build/intermediates/apk/debug/app-debug-2.0.0.apk
          asset_name: Example.apk
          asset_content_type: application/zip

